---
  version: '3.3'

  secrets:
    tomcat_ssl_crt:
      file: ./certificates/tomcat/tomcat-wildcard-dev.crt
    tomcat_ssl_key:
      file: ./certificates/tomcat/tomcat-wildcard-dev.key

  services:
    qw_portal_services:
      build: .
      image: qw_portal_services
      ports:
        - "8082:8080"
      secrets:
        - source: tomcat_ssl_crt
          target: /home/spring/tomcat-wildcard-ssl.crt
        - source: tomcat_ssl_key
          target: /home/spring/tomcat-wildcard-ssl.key
      env_file:
        - config.env
        - secrets.env