# docker image path in artifactory
artifactoryPath: "qw_portal_services"
# docker image path in gitlab
gitlabPath: "wma/docker/wqp"
# name of the docker image
dockerImageName: "qw_portal_services"
# type of build
repoPath: "NWQMC/qw_portal_services"
# name of the git repo
gitRepoUrl: "https://github.com/NWQMC/qw_portal_services.git"
# Jenkins credential for pushing back to repo
gitRepoCredentialsId: "Jenkins-GitHub-Read-Write-Token"
# name of the deploy job to trigger
deployJobName: "qw-portal-services-deploy"
# name of the project
projectName: "wqp-external"
# maximum amount of RAM for running Docker containers in the service
memory: 512
# name of the application or service
applicationName: "qw_portal_services"
# integer representing the order of precedence of the ALB rule.
# set to a low priority; services are given higher priority.
rulePriority: 502
# port that is exposed by your container
containerPort: 8080
# string parameter specifying a path that ALB should use to verify that your application is alive
healthCheck: "/Codes/actuator/health"
# string parameter that tells the ALB how to route requests to the containers (e.g. /my-app/*); this forms a listener rule for the load balancer
contextPath: "/Codes/*"
# configuration repository paths
configRepoPath: "wma/docker/wqp/qw_portal_services"
configCredentialsId: "wma-eto-eb-rsa"
