
spring:
  datasource:
    url: "jdbc:postgresql://${wqpDbHost}:${wqpDbPort}/${wqpDbName}"
    username: ${wqpDbUsername}
    password: ${wqpDbUserPassword}
    
  profiles:
    active: default,swagger
    
server:
  port: ${serverPort}
  servlet:
    context-path: ${serverContextPath}
 
qwPortalServices:
  displayHost: ${qwDisplayHost}
  displayPath: ${qwDisplayPath}
  displayProtocol: ${qwDisplayProtocol}
  
swaggerServicesConfigFile: classpath:/swaggerServices.yml
  
