
spring:
  datasource:
    jndi-name: "java:comp/env/jdbc/WQPQW"

  profiles:
    active: default, swagger

management:
  info:
    git:
      mode: full

logging:
  config: classpath:/logback-spring.xml
