
spring:
  datasource:
    url: jdbc:postgresql://${WQP_DATABASE_ADDRESS}:${WQP_DATABASE_PORT}/${WQP_DATABASE_NAME}
    username: ${WQP_DB_READ_ONLY_USERNAME}
    password: ${WQP_DB_READ_ONLY_PASSWORD}

  profiles:
    active: default,swagger

server:
  port: ${SERVER_PORT}
  servlet:
    context-path: ${SERVER_CONTEXT_PATH}

codes:
  service:
    url: ${CODES_SERVICE_URL}

logging:
  level:
    root: ${ROOT_LOG_LEVEL}

management:
  endpoints:
    enabled-by-default: false
    jmx:
      exposure:
        exclude: "*"
    web:
      base-path: /about
      exposure:
        include:
        - info
        - health
  endpoint:
    info:
      enabled: true
    health:
      enabled: true
      show-details: never
