
spring:
  datasource:
    url: jdbc:postgresql://${DATABASE_ADDRESS}:${DATABASE_PORT}/${DATABASE_NAME}?currentSchema=${SCHEMA_NAME}
    username: ${READ_ONLY_USERNAME}
    password: ${READ_ONLY_PASSWORD}

springdoc:
  version: "@project.version@"

server:
  port: ${SERVER_PORT}
  servlet:
    context-path: ${SERVER_CONTEXT_PATH}

codes:
  service:
    url: ${CODES_SERVICE_URL}
  swagger:
    apiDocsUrl: ${SERVER_CONTEXT_PATH}/v3/api-docs
    deployName: ${DEPLOY_NAME}

logging:
  level:
    root: ${ROOT_LOG_LEVEL:INFO}
    javax.management.mbeanserver: OFF

management:
  endpoints:
    enabled-by-default: false
    jmx:
      exposure:
        exclude: "*"
    web:
      base-path: /about
      exposure:
        include:
        - info
        - health
  endpoint:
    info:
      enabled: true
    health:
      enabled: true
      show-details: never
