
spring:
  datasource:
    url: "jdbc:postgresql://${wqpDbHost}:${wqpDbPort}/wqp_core"
    username: ${wqpDbUsername}
    password: ${wqpDbUserPassword}
    
  profiles:
    active: default,swagger
 
qwPortalServices:
  displayHost: ${qwDisplayHost}
  displayPath: ${qwDisplayPath}
  
swaggerServicesConfigFile: classpath:/swaggerServices.yml
  
