# SAMPLE Swagger Services Configuration for WQP
services:
  - 
    name: Lookups
    url: 'http://localhost:8082/qw_portal_services/v2/api-docs'
    version: 2.0
  -
    name: WQP
    url: 'http://localhost:8080/wqp/v2/api-docs'
    version: 2.0
  -
    name: NLDI
    url: 'https://cida.usgs.gov/nldi/v2/api-docs'
    version: 2.0
